vim = vim or require('vim')
require('plugins')
require('options')
require('plugins.dressing')
require('plugins.autosession')
require('plugins.lualine')
require('plugins.nvimtree')
require('plugins.treesitter')
require('plugins.comment')
require('plugins.cmp')
require('plugins.lsp-zero')
require('plugins.telescope')
require('plugins.copilot')

print("Hello myself!")
