#!/bin/sh
###
# Installation of NeoVim configuration
#
# @author Manne Busk
###
BLACK='\033[0;30m'        # Black
RED='\033[0;31m'          # Red
GREEN='\033[0;32m'        # Green
YELLOW='\033[0;33m'       # Yellow
BLUE='\033[0;34m'         # Blue
PURPLE='\033[0;35m'       # Purple
CYAN='\033[0;36m'         # Cyan
WHITE='\033[0;37m'        # White
NORMAL='\033[0m'       # Text Reset

DIR="$( cd "$( dirname "$0" )" && pwd )"
PLUG=~/.local/share/nvim/site/autoload/plug.vim 
if [ -f $PLUG ]; then
    echo $CYAN"Plugin manager already installed at "$NORMAL"~/.local/share/nvim/site/autoload/plug.vim"
else
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    echo $GREEN"Plugin manager installed into "$NORMAL"~/.local/share/nvim/site/autoload/plug.vim"
fi

INIT=~/.config/nvim/init.vim
if [ -f $INIT ]; then
    echo $CYAN"NeoVim configuration already exists in "$NORMAL"~/.config/nvim/init.vim"
    echo $RED"FAILED"$NORMAL
    echo $CYAN"Please remove existing configuration and run this script again."$NORMAL
else
    mkdir -p ~/.config/nvim
    ln -s $DIR/init.vim ~/.config/nvim/init.vim
    echo $GREEN"NeoVim configuraion linked into "$NORMAL"~/.config/nvim/init.vim"
    echo $GREEN"Complete!"$NORMAL
fi

INIT_SNIPPETS=~/.config/nvim/snippets/vim.snippets
if [ -f $INIT_SNIPPETS ]; then
    echo $CYAN"Snippets already linked to "$NORMAL"~/.config/nvim/snippets/"
    echo $RED"FAILED"$NORMAL
else
    ln -s $DIR/snippets ~/.config/nvim/snippets
    echo $GREEN"Snippets linked into "$NORMAL"~/.config/nvim/snippets/"
    echo $GREEN"Complete!"$NORMAL
fi

INIT_FTPLUGIN=~/.config/nvim/ftplugin
if [ -d $INIT_FTPLUGIN ]; then
    echo $CYAN"ftplugin folder already exists in "$NORMAL"~/.config/nvim/ftplugin/"
    echo $RED"FAILED"$NORMAL
else
    ln -s $DIR/ftplugin ~/.config/nvim/ftplugin
    echo $GREEN"ftplugin folder linked into "$NORMAL"~/.config/nvim/ftplugin/"
    echo $GREEN"Complete!"$NORMAL
fi

COC_SETTINGS=~/.config/nvim/coc-settings.json
if [ -f $COC_SETTINGS ]; then
    echo $CYAN"coc-settings.json already exists at "$NORMAL"~/.config/nvim/coc-settings.json"
    echo $RED"FAILED"$NORMAL
    echo $CYAN"Please remove existing configuration and run this script again to link it"$NORMAL
else
    ln -s $DIR/coc-settings.json ~/.config/nvim/coc-settings.json
    echo $GREEN"coc-settings linked into "$NORMAL"~/.config/nvim/coc-settings.json"
    echo $GREEN"Complete!"$NORMAL
fi
